/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.demo.nightcare;
import java.awt.Font;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;


/**
 *
 * @author virginia
 */
public class MainFrame extends javax.swing.JFrame {
    private int selectedRowIndex = -1;
    private TableModel selectedTableModel = null;
    private List<Child> children;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        DefaultTableModel t = (DefaultTableModel)studentsTable.getModel(); 
        
        DataHandler dataHandler = new DataHandler();
        dataHandler.loadData();
        children = dataHandler.children;
        for (Child c : children) {
            t.addRow(c.getInfo());
        }
        
        JTableHeader jtb = studentsTable.getTableHeader();
        jtb.setFont(new Font("Helvetica", Font.BOLD, 20));
        this.setResizable(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JTabbedPane();
        StudentPane = new javax.swing.JPanel();
        studentsScrollPane = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        studentsInputPanel = new javax.swing.JPanel();
        studentIdLabel = new javax.swing.JLabel();
        studentIdTextField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        classTextField = new javax.swing.JTextField();
        immunizationLabel = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        deleteButton = new javax.swing.JButton();
        TeacherPane = new javax.swing.JPanel();
        teacherScrollPane = new javax.swing.JScrollPane();
        teachersTable = new javax.swing.JTable();
        teachersInputPanel = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        idTextField1 = new javax.swing.JTextField();
        NameLabel1 = new javax.swing.JLabel();
        nameTextField1 = new javax.swing.JTextField();
        classLabel1 = new javax.swing.JLabel();
        classTextField1 = new javax.swing.JTextField();
        classTextField2 = new javax.swing.JTextField();
        classLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentsTable.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsTableMouseClicked(evt);
            }
        });
        studentsScrollPane.setViewportView(studentsTable);

        studentIdLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        studentIdLabel.setText("ID");
        studentIdLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        studentIdTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        NameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NameLabel.setText("Name");
        NameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        ageLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        ageLabel.setText("Age");
        ageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ageTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        classLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        classLabel.setText("Class");
        classLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        classTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        immunizationLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        immunizationLabel.setText("Immunization");
        immunizationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POLIO", "MMR", "HEPATITIS_B", "VARICELLA", "DTAP" }));

        deleteButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentsInputPanelLayout = new javax.swing.GroupLayout(studentsInputPanel);
        studentsInputPanel.setLayout(studentsInputPanelLayout);
        studentsInputPanelLayout.setHorizontalGroup(
            studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentsInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentsInputPanelLayout.createSequentialGroup()
                        .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentsInputPanelLayout.createSequentialGroup()
                        .addComponent(studentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIdTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentsInputPanelLayout.createSequentialGroup()
                        .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(nameTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentsInputPanelLayout.createSequentialGroup()
                        .addComponent(immunizationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentsInputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        studentsInputPanelLayout.setVerticalGroup(
            studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentsInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentIdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(immunizationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(studentsInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout StudentPaneLayout = new javax.swing.GroupLayout(StudentPane);
        StudentPane.setLayout(StudentPaneLayout);
        StudentPaneLayout.setHorizontalGroup(
            StudentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentsInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StudentPaneLayout.setVerticalGroup(
            StudentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPaneLayout.createSequentialGroup()
                        .addComponent(studentsInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(studentsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)))
        );

        MainPane.addTab("Students", StudentPane);

        teachersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Salary", "Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        teacherScrollPane.setViewportView(teachersTable);

        idLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        idLabel1.setText("ID");
        idLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        idTextField1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        NameLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        NameLabel1.setText("Name");
        NameLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameTextField1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        classLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        classLabel1.setText("Class");
        classLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        classTextField1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        classTextField2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N

        classLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        classLabel2.setText("Salary");
        classLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout teachersInputPanelLayout = new javax.swing.GroupLayout(teachersInputPanel);
        teachersInputPanel.setLayout(teachersInputPanelLayout);
        teachersInputPanelLayout.setHorizontalGroup(
            teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachersInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teachersInputPanelLayout.createSequentialGroup()
                        .addComponent(classLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classTextField2))
                    .addGroup(teachersInputPanelLayout.createSequentialGroup()
                        .addComponent(classLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                    .addGroup(teachersInputPanelLayout.createSequentialGroup()
                        .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField1))
                    .addGroup(teachersInputPanelLayout.createSequentialGroup()
                        .addComponent(NameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTextField1)))
                .addGap(12, 12, 12))
        );
        teachersInputPanelLayout.setVerticalGroup(
            teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachersInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teachersInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(classLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(classTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TeacherPaneLayout = new javax.swing.GroupLayout(TeacherPane);
        TeacherPane.setLayout(TeacherPaneLayout);
        TeacherPaneLayout.setHorizontalGroup(
            TeacherPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teachersInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TeacherPaneLayout.setVerticalGroup(
            TeacherPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeacherPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teachersInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacherScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainPane.addTab("Teachers", TeacherPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsTableMouseClicked
        // TODO add your handling code here:
        int i = studentsTable.getSelectedRow();
        selectedRowIndex = i;
        TableModel selectedModel = studentsTable.getModel();
        selectedTableModel = selectedModel;
        studentIdTextField.setText(selectedModel.getValueAt(i,0).toString());
        nameTextField.setText(selectedModel.getValueAt(i,1).toString());
        ageTextField.setText(selectedModel.getValueAt(i,2).toString());
    }//GEN-LAST:event_studentsTableMouseClicked

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        studentIdTextField.setText("");
        ageTextField.setText("");
        nameTextField.setText("");
        classTextField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        selectedTableModel.setValueAt(studentIdTextField.getText(),selectedRowIndex,0);
        selectedTableModel.setValueAt(nameTextField.getText(),selectedRowIndex,1);
        selectedTableModel.setValueAt(ageTextField.getText(),selectedRowIndex,2);
        
        studentIdTextField.setText("");
        ageTextField.setText("");
        nameTextField.setText("");
        classTextField.setText("");
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t = (DefaultTableModel)studentsTable.getModel(); 
        t.removeRow(selectedRowIndex);
        
        studentIdTextField.setText("");
        ageTextField.setText("");
        nameTextField.setText("");
        classTextField.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //DefaultTableModel t = (DefaultTableModel)studentsTable.getModel();
                
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JPanel StudentPane;
    private javax.swing.JPanel TeacherPane;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel classLabel;
    private javax.swing.JLabel classLabel1;
    private javax.swing.JLabel classLabel2;
    private javax.swing.JTextField classTextField;
    private javax.swing.JTextField classTextField1;
    private javax.swing.JTextField classTextField2;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JLabel immunizationLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextField1;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JTextField studentIdTextField;
    private javax.swing.JPanel studentsInputPanel;
    private javax.swing.JScrollPane studentsScrollPane;
    private javax.swing.JTable studentsTable;
    private javax.swing.JScrollPane teacherScrollPane;
    private javax.swing.JPanel teachersInputPanel;
    private javax.swing.JTable teachersTable;
    // End of variables declaration//GEN-END:variables
}
